workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      android_signing:
        - karl_key
      groups:
        - firebase_credentials
      vars:
        PACKAGE_NAME: "io.codemagic.karlapp"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release --build-name=1.0.4
      - name: Build APK with Flutter
        script: |
          flutter build apk --release --build-name=1.0.4
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - tamm.karl.kristjan@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:818970529704:android:abaa156a71cbeebdcf179d
          groups:
            - test1
          artifact_type: 'apk'